### ISSUE TITLE
replace it with another weakly-supervised text classification model

### ISSUE THREAD

**Issue by 874061490** [YipingNUS/OptimSeed#1]
hello, how to replace it with another weakly-supervised text classification model

**Comment by YipingNUS** [comment]
Hi, the third step Bayesian error estimation just takes a numpy array of dimensions [num_samples, num_estimators]. Each entry is either 0 or 1, which is the prediction from the weakly-supervised binary classifiers.

The framework assumes the weakly-supervised classifier (interim classifiers) can be trained using a single (+/-) keyword pair. Therefore, you should probably use some strong classifier baseline instead of naive ones like keyword voting.

**Comment by 874061490** [comment]
Thank you for your reply
